#Un servicio que dentro tenga python y pip-instale dbt
#Otro servicio que tenga la base (postgres).
#Un volumen para poder inicializar la base con la data cruda 
#Otro volumen para poder crear los modelos por fuera del container

version: "3"

services:
  dbt:
    container_name: dbt
    build:
      context: ./container_python_dbt
    stdin_open: true # docker run -i
    volumes:
      - ./container_python_dbt/:/usr/src/app/
    ports:
        - "8080:8080"
    
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=pipol
      - POSTGRES_DB=mercados_latam
    volumes:
      - ./container_db/scripts:/docker-entrypoint-initdb.d
      - ./container_db/:/container_db/
  
